server:
  port: 8003
  servlet:
    context-path: /user
spring:
  application:
    name: coffee-user
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/coffee?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

redis:
  host: 127.0.0.1:6379
  timeout: 3000

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka/
    register-with-eureka: true
    fetch-registry: true


mybatis:
  type-aliases-package: com.wyz.coffee.entity
  mapper-locations: classpath:mapping/*.xml,classpath:mapping/generated/*.xml

logging:
  config: classpath:logback.xml
  level:
    com.wyz.coffee: debug
